# Changes here will be overwritten by Copier
AnswerStrategy: recommended
AuthorEmail: abel.s.siqueira@gmail.com
AuthorName: Abel Soares Siqueira
Indentation: 2
JuliaMinVersion: '1.6'
License: MPL-2.0
PackageName: COPIERTemplateExample
PackageOwner: abelsiqueira
PackageUUID: d7deeeea-80e8-4f78-bbba-6981ece9d3d5
_commit: v0.5.4
_src_path: https://github.com/abelsiqueira/COPIERTemplate.jl
